# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
